# Generated automatically from Makefile.in by configure.
include $(TOPDIR)/src/Make.conf

install: dummy
	- $(INSTALL_DIR) $(DOCDIR)
	- for i in $(DOCS1) $(DOCS3); do $(INSTALL_DATA) $(TOPDIR)/doc/$$i $(DOCDIR)/$$i; done 
	- for i in $(DOCS2); do $(INSTALL_DATA) $(TOPDIR)/$$i $(DOCDIR)/$$i; done 

clean:

realclean: clean

include $(TOPDIR)/src/rules.mk
